//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A5Soft.A5App.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A5Soft.A5App.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the document as a user {0} has updated it while you were editing..
        /// </summary>
        public static string ConcurrencyException_Message {
            get {
                return ResourceManager.GetString("ConcurrencyException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either {0} or {1} should be specified..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_AtLeastOneRequired {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_AtLeastOneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match {1}..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_CompareStrings {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_CompareStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is either in future or way too far in past..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_DateSanity {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_DateSanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} is not a valid email address..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_EmailAddress {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} cannot exceed {2}..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_Range_ForMax {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_Range_ForMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} cannot be less than {1}..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_Range_ForMin {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_Range_ForMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} should be between {1} and {2}..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_Range_ForRange {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_Range_ForRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not specified..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_Required {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of {0} shall be {1} characters..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_StringLength_ForExact {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_StringLength_ForExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of {0} shall not exceed {2} characters..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_StringLength_ForMax {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_StringLength_ForMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of {0} shall be between {1} and {2} characters..
        /// </summary>
        public static string DataAnnotations_ErrorMessage_StringLength_ForRange {
            get {
                return ResourceManager.GetString("DataAnnotations_ErrorMessage_StringLength_ForRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trace.
        /// </summary>
        public static string IAuditableEntity_GroupName {
            get {
                return ResourceManager.GetString("IAuditableEntity_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the data has been inserted..
        /// </summary>
        public static string IAuditableEntity_InsertedAt_Description {
            get {
                return ResourceManager.GetString("IAuditableEntity_InsertedAt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted At.
        /// </summary>
        public static string IAuditableEntity_InsertedAt_Name {
            get {
                return ResourceManager.GetString("IAuditableEntity_InsertedAt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted At.
        /// </summary>
        public static string IAuditableEntity_InsertedAt_ShortName {
            get {
                return ResourceManager.GetString("IAuditableEntity_InsertedAt_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email of the user who inserted the data..
        /// </summary>
        public static string IAuditableEntity_InsertedBy_Description {
            get {
                return ResourceManager.GetString("IAuditableEntity_InsertedBy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted By.
        /// </summary>
        public static string IAuditableEntity_InsertedBy_Name {
            get {
                return ResourceManager.GetString("IAuditableEntity_InsertedBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted By.
        /// </summary>
        public static string IAuditableEntity_InsertedBy_ShortName {
            get {
                return ResourceManager.GetString("IAuditableEntity_InsertedBy_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the data has been updated last..
        /// </summary>
        public static string IAuditableEntity_UpdatedAt_Description {
            get {
                return ResourceManager.GetString("IAuditableEntity_UpdatedAt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string IAuditableEntity_UpdatedAt_Name {
            get {
                return ResourceManager.GetString("IAuditableEntity_UpdatedAt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string IAuditableEntity_UpdatedAt_ShortName {
            get {
                return ResourceManager.GetString("IAuditableEntity_UpdatedAt_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email of the last user who updated the data..
        /// </summary>
        public static string IAuditableEntity_UpdatedBy_Description {
            get {
                return ResourceManager.GetString("IAuditableEntity_UpdatedBy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string IAuditableEntity_UpdatedBy_Name {
            get {
                return ResourceManager.GetString("IAuditableEntity_UpdatedBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string IAuditableEntity_UpdatedBy_ShortName {
            get {
                return ResourceManager.GetString("IAuditableEntity_UpdatedBy_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with an admin priviledge is authorized to perform any administrative action as well as any action for any tenant..
        /// </summary>
        public static string Security_AdministrativeRole_Admin_Description {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_Admin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Administrator.
        /// </summary>
        public static string Security_AdministrativeRole_Admin_Name {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_Admin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Security_AdministrativeRole_Admin_ShortName {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_Admin_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with an user group admin priviledge is authorized to perform any action for the tenants that are assigned to the user group as well as manage users that are assigned to the user group..
        /// </summary>
        public static string Security_AdministrativeRole_GroupAdmin_Description {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_GroupAdmin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Administrator.
        /// </summary>
        public static string Security_AdministrativeRole_GroupAdmin_Name {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_GroupAdmin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Admin.
        /// </summary>
        public static string Security_AdministrativeRole_GroupAdmin_ShortName {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_GroupAdmin_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with no admin priviledges is only authorized to perform actions for tenants subject to their roles for the respective tenants..
        /// </summary>
        public static string Security_AdministrativeRole_None_Description {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_None_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Security_AdministrativeRole_None_Name {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_None_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Security_AdministrativeRole_None_ShortName {
            get {
                return ResourceManager.GetString("Security_AdministrativeRole_None_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password       .
        /// </summary>
        public static string Security_ChangePasswordRequest_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequest_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user password..
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_CurrentPassword_Description {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_CurrentPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_CurrentPassword_Name {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_CurrentPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.       .
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_CurrentPassword_Prompt {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_CurrentPassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_CurrentPassword_ShortName {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_CurrentPassword_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user password..
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_NewPassword_Description {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_NewPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_NewPassword_Name {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_NewPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.       .
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_NewPassword_Prompt {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_NewPassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_NewPassword_ShortName {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_NewPassword_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated new user password..
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_Description {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat New Password.
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_Name {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password..
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_Prompt {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat New Password.
        /// </summary>
        public static string Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_ShortName {
            get {
                return ResourceManager.GetString("Security_ChangePasswordRequestQueryCriteria_RepeatedPassword_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Custom Role.
        /// </summary>
        public static string Security_ICustomUserRole_DisplayNameForCreateNew {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_DisplayNameForCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Custom Role For Tenant.
        /// </summary>
        public static string Security_ICustomUserRole_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Custom Role For Tenant.
        /// </summary>
        public static string Security_ICustomUserRole_DisplayNameForOld {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_DisplayNameForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of permissions for the user to have while managing the tenant data..
        /// </summary>
        public static string Security_ICustomUserRole_Permissions_Description {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_Permissions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Security_ICustomUserRole_Permissions_Name {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_Permissions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Security_ICustomUserRole_Permissions_ShortName {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_Permissions_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the tenant whom the custom user role is configured for..
        /// </summary>
        public static string Security_ICustomUserRole_TenantName_Description {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_TenantName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string Security_ICustomUserRole_TenantName_Name {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_TenantName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Security_ICustomUserRole_TenantName_ShortName {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_TenantName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the user whom the custom role is configured for..
        /// </summary>
        public static string Security_ICustomUserRole_UserName_Description {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_UserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Security_ICustomUserRole_UserName_Name {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_UserName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User   .
        /// </summary>
        public static string Security_ICustomUserRole_UserName_ShortName {
            get {
                return ResourceManager.GetString("Security_ICustomUserRole_UserName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the database where the client company data is stored..
        /// </summary>
        public static string Security_ITenant_DatabaseName_Description {
            get {
                return ResourceManager.GetString("Security_ITenant_DatabaseName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string Security_ITenant_DatabaseName_Name {
            get {
                return ResourceManager.GetString("Security_ITenant_DatabaseName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify tenant database name..
        /// </summary>
        public static string Security_ITenant_DatabaseName_Prompt {
            get {
                return ResourceManager.GetString("Security_ITenant_DatabaseName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Security_ITenant_DatabaseName_ShortName {
            get {
                return ResourceManager.GetString("Security_ITenant_DatabaseName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tenant       .
        /// </summary>
        public static string Security_ITenant_DisplayNameForCreateNew {
            get {
                return ResourceManager.GetString("Security_ITenant_DisplayNameForCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tenant.
        /// </summary>
        public static string Security_ITenant_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_ITenant_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Security_ITenant_DisplayNameForOld {
            get {
                return ResourceManager.GetString("Security_ITenant_DisplayNameForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the client company which data is stored in an app database..
        /// </summary>
        public static string Security_ITenant_Name_Description {
            get {
                return ResourceManager.GetString("Security_ITenant_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string Security_ITenant_Name_Name {
            get {
                return ResourceManager.GetString("Security_ITenant_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify tenant name.       .
        /// </summary>
        public static string Security_ITenant_Name_Prompt {
            get {
                return ResourceManager.GetString("Security_ITenant_Name_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Security_ITenant_Name_ShortName {
            get {
                return ResourceManager.GetString("Security_ITenant_Name_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Group.
        /// </summary>
        public static string Security_ITenantGroupAssignment_DisplayNameForCreateNew {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignment_DisplayNameForCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user group that the tenant is assigned to..
        /// </summary>
        public static string Security_ITenantGroupAssignment_Group_Description {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignment_Group_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string Security_ITenantGroupAssignment_Group_Name {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignment_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string Security_ITenantGroupAssignment_Group_ShortName {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignment_Group_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of assignments..
        /// </summary>
        public static string Security_ITenantGroupAssignments_Assignments_Description {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_Assignments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string Security_ITenantGroupAssignments_Assignments_Name {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_Assignments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user groups to assign the tenant to..
        /// </summary>
        public static string Security_ITenantGroupAssignments_Assignments_Prompt {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_Assignments_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string Security_ITenantGroupAssignments_Assignments_ShortName {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_Assignments_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant User Group Assignments       .
        /// </summary>
        public static string Security_ITenantGroupAssignments_DisplayNameForOld {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_DisplayNameForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the tenant to manage user group assignments for..
        /// </summary>
        public static string Security_ITenantGroupAssignments_TenantName_Description {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_TenantName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string Security_ITenantGroupAssignments_TenantName_Name {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_TenantName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string Security_ITenantGroupAssignments_TenantName_ShortName {
            get {
                return ResourceManager.GetString("Security_ITenantGroupAssignments_TenantName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative role of the user..
        /// </summary>
        public static string Security_IUser_AdminRole_Description {
            get {
                return ResourceManager.GetString("Security_IUser_AdminRole_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Role.
        /// </summary>
        public static string Security_IUser_AdminRole_Name {
            get {
                return ResourceManager.GetString("Security_IUser_AdminRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user administrative role.       .
        /// </summary>
        public static string Security_IUser_AdminRole_Prompt {
            get {
                return ResourceManager.GetString("Security_IUser_AdminRole_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Role.
        /// </summary>
        public static string Security_IUser_AdminRole_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_AdminRole_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User       .
        /// </summary>
        public static string Security_IUser_DisplayNameForCreateNew {
            get {
                return ResourceManager.GetString("Security_IUser_DisplayNameForCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string Security_IUser_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_IUser_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Security_IUser_DisplayNameForOld {
            get {
                return ResourceManager.GetString("Security_IUser_DisplayNameForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email of the user that is also used as a user name for login..
        /// </summary>
        public static string Security_IUser_Email_Description {
            get {
                return ResourceManager.GetString("Security_IUser_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Security_IUser_Email_Name {
            get {
                return ResourceManager.GetString("Security_IUser_Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user email.       .
        /// </summary>
        public static string Security_IUser_Email_Prompt {
            get {
                return ResourceManager.GetString("Security_IUser_Email_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Security_IUser_Email_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_Email_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the user is disabled, i.e. no longer in use, only left as a historic record..
        /// </summary>
        public static string Security_IUser_IsDisabled_Description {
            get {
                return ResourceManager.GetString("Security_IUser_IsDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Disabled.
        /// </summary>
        public static string Security_IUser_IsDisabled_Name {
            get {
                return ResourceManager.GetString("Security_IUser_IsDisabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled       .
        /// </summary>
        public static string Security_IUser_IsDisabled_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_IsDisabled_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the user is (temporaly) suspended. Suspended users only have readonly privileges (irrespective of their configured roles)..
        /// </summary>
        public static string Security_IUser_IsSuspended_Description {
            get {
                return ResourceManager.GetString("Security_IUser_IsSuspended_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Suspended.
        /// </summary>
        public static string Security_IUser_IsSuspended_Name {
            get {
                return ResourceManager.GetString("Security_IUser_IsSuspended_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended       .
        /// </summary>
        public static string Security_IUser_IsSuspended_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_IsSuspended_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A given name of the user..
        /// </summary>
        public static string Security_IUser_Name_Description {
            get {
                return ResourceManager.GetString("Security_IUser_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name.
        /// </summary>
        public static string Security_IUser_Name_Name {
            get {
                return ResourceManager.GetString("Security_IUser_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user (given) name.       .
        /// </summary>
        public static string Security_IUser_Name_Prompt {
            get {
                return ResourceManager.GetString("Security_IUser_Name_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Security_IUser_Name_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_Name_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A phone No of the user..
        /// </summary>
        public static string Security_IUser_Phone_Description {
            get {
                return ResourceManager.GetString("Security_IUser_Phone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string Security_IUser_Phone_Name {
            get {
                return ResourceManager.GetString("Security_IUser_Phone_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user phone.       .
        /// </summary>
        public static string Security_IUser_Phone_Prompt {
            get {
                return ResourceManager.GetString("Security_IUser_Phone_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Security_IUser_Phone_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_Phone_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure user roles per tenant (for users with no administrative privileges)..
        /// </summary>
        public static string Security_IUser_RolesForTenants_Description {
            get {
                return ResourceManager.GetString("Security_IUser_RolesForTenants_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles For Tenants.
        /// </summary>
        public static string Security_IUser_RolesForTenants_Name {
            get {
                return ResourceManager.GetString("Security_IUser_RolesForTenants_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure user roles per tenant (for users with no administrative privileges)..
        /// </summary>
        public static string Security_IUser_RolesForTenants_Prompt {
            get {
                return ResourceManager.GetString("Security_IUser_RolesForTenants_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles For Tenants.
        /// </summary>
        public static string Security_IUser_RolesForTenants_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_RolesForTenants_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to require two factor authentication for the user. E.g. when a particular user works from an unsafe environment..
        /// </summary>
        public static string Security_IUser_TwoFactorEnabled_Description {
            get {
                return ResourceManager.GetString("Security_IUser_TwoFactorEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Two Factor Authentication.
        /// </summary>
        public static string Security_IUser_TwoFactorEnabled_Name {
            get {
                return ResourceManager.GetString("Security_IUser_TwoFactorEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Two Factor Authentication       .
        /// </summary>
        public static string Security_IUser_TwoFactorEnabled_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_TwoFactorEnabled_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An user group that the user belongs to (if any)..
        /// </summary>
        public static string Security_IUser_UserGroup_Description {
            get {
                return ResourceManager.GetString("Security_IUser_UserGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string Security_IUser_UserGroup_Name {
            get {
                return ResourceManager.GetString("Security_IUser_UserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the user group for the user (if any)       .
        /// </summary>
        public static string Security_IUser_UserGroup_Prompt {
            get {
                return ResourceManager.GetString("Security_IUser_UserGroup_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Security_IUser_UserGroup_ShortName {
            get {
                return ResourceManager.GetString("Security_IUser_UserGroup_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Group.
        /// </summary>
        public static string Security_IUserGroup_DisplayNameForCreateNew {
            get {
                return ResourceManager.GetString("Security_IUserGroup_DisplayNameForCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Group.
        /// </summary>
        public static string Security_IUserGroup_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_IUserGroup_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string Security_IUserGroup_DisplayNameForOld {
            get {
                return ResourceManager.GetString("Security_IUserGroup_DisplayNameForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An arbitrary user group name for human friendly reference..
        /// </summary>
        public static string Security_IUserGroup_GroupName_Description {
            get {
                return ResourceManager.GetString("Security_IUserGroup_GroupName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Security_IUserGroup_GroupName_Name {
            get {
                return ResourceManager.GetString("Security_IUserGroup_GroupName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user group name.
        /// </summary>
        public static string Security_IUserGroup_GroupName_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserGroup_GroupName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Security_IUserGroup_GroupName_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserGroup_GroupName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed tenants within the group..
        /// </summary>
        public static string Security_IUserGroup_MaxTenants_Description {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxTenants_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max tenants per group.
        /// </summary>
        public static string Security_IUserGroup_MaxTenants_Name {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxTenants_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify max allowed tenants within the group.
        /// </summary>
        public static string Security_IUserGroup_MaxTenants_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxTenants_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max tenants.
        /// </summary>
        public static string Security_IUserGroup_MaxTenants_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxTenants_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed users within the group..
        /// </summary>
        public static string Security_IUserGroup_MaxUsers_Description {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max users per group.
        /// </summary>
        public static string Security_IUserGroup_MaxUsers_Name {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxUsers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify max allowed users within the group.
        /// </summary>
        public static string Security_IUserGroup_MaxUsers_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxUsers_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max users.
        /// </summary>
        public static string Security_IUserGroup_MaxUsers_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserGroup_MaxUsers_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual count of users assigned to the group..
        /// </summary>
        public static string Security_IUserGroup_UserCount_Description {
            get {
                return ResourceManager.GetString("Security_IUserGroup_UserCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string Security_IUserGroup_UserCount_Name {
            get {
                return ResourceManager.GetString("Security_IUserGroup_UserCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Security_IUserGroup_UserCount_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserGroup_UserCount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the user has the permission..
        /// </summary>
        public static string Security_IUserPermission_Assigned_Description {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Assigned_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assigned.
        /// </summary>
        public static string Security_IUserPermission_Assigned_Name {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Assigned_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assigned.
        /// </summary>
        public static string Security_IUserPermission_Assigned_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Assigned_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the assignable permission..
        /// </summary>
        public static string Security_IUserPermission_Description_Description {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Security_IUserPermission_Description_Name {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description       .
        /// </summary>
        public static string Security_IUserPermission_Description_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Description_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the permission group that the permission belongs to..
        /// </summary>
        public static string Security_IUserPermission_GroupName_Description {
            get {
                return ResourceManager.GetString("Security_IUserPermission_GroupName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Group Name.
        /// </summary>
        public static string Security_IUserPermission_GroupName_Name {
            get {
                return ResourceManager.GetString("Security_IUserPermission_GroupName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name       .
        /// </summary>
        public static string Security_IUserPermission_GroupName_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserPermission_GroupName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the application module that the permission belongs to..
        /// </summary>
        public static string Security_IUserPermission_ModuleName_Description {
            get {
                return ResourceManager.GetString("Security_IUserPermission_ModuleName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string Security_IUserPermission_ModuleName_Name {
            get {
                return ResourceManager.GetString("Security_IUserPermission_ModuleName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Security_IUserPermission_ModuleName_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserPermission_ModuleName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the assignable permission..
        /// </summary>
        public static string Security_IUserPermission_Name_Description {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name.
        /// </summary>
        public static string Security_IUserPermission_Name_Name {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Security_IUserPermission_Name_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserPermission_Name_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the role that is displayed as a tooltip for lookup values..
        /// </summary>
        public static string Security_IUserRole_Description_Description {
            get {
                return ResourceManager.GetString("Security_IUserRole_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Description.
        /// </summary>
        public static string Security_IUserRole_Description_Name {
            get {
                return ResourceManager.GetString("Security_IUserRole_Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify role description       .
        /// </summary>
        public static string Security_IUserRole_Description_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserRole_Description_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Security_IUserRole_Description_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRole_Description_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Role       .
        /// </summary>
        public static string Security_IUserRole_DisplayNameForCreateNew {
            get {
                return ResourceManager.GetString("Security_IUserRole_DisplayNameForCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Role.
        /// </summary>
        public static string Security_IUserRole_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_IUserRole_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string Security_IUserRole_DisplayNameForOld {
            get {
                return ResourceManager.GetString("Security_IUserRole_DisplayNameForOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A human readable name that is displayed in a lookup for a role assignment..
        /// </summary>
        public static string Security_IUserRole_Name_Description {
            get {
                return ResourceManager.GetString("Security_IUserRole_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Name.
        /// </summary>
        public static string Security_IUserRole_Name_Name {
            get {
                return ResourceManager.GetString("Security_IUserRole_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify role name       .
        /// </summary>
        public static string Security_IUserRole_Name_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserRole_Name_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Security_IUserRole_Name_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRole_Name_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of permissions that will be assigned to a user for this role..
        /// </summary>
        public static string Security_IUserRole_Permissions_Description {
            get {
                return ResourceManager.GetString("Security_IUserRole_Permissions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions For User Role.
        /// </summary>
        public static string Security_IUserRole_Permissions_Name {
            get {
                return ResourceManager.GetString("Security_IUserRole_Permissions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify role permissions.
        /// </summary>
        public static string Security_IUserRole_Permissions_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserRole_Permissions_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Security_IUserRole_Permissions_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRole_Permissions_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number of users (excluding disabled) that have the role assigned..
        /// </summary>
        public static string Security_IUserRole_UserCount_Description {
            get {
                return ResourceManager.GetString("Security_IUserRole_UserCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string Security_IUserRole_UserCount_Name {
            get {
                return ResourceManager.GetString("Security_IUserRole_UserCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Security_IUserRole_UserCount_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRole_UserCount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the user role has the permission..
        /// </summary>
        public static string Security_IUserRolePermission_Assigned_Description {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Assigned_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assigned.
        /// </summary>
        public static string Security_IUserRolePermission_Assigned_Name {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Assigned_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assigned.
        /// </summary>
        public static string Security_IUserRolePermission_Assigned_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Assigned_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the assignable permission..
        /// </summary>
        public static string Security_IUserRolePermission_Description_Description {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Security_IUserRolePermission_Description_Name {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Description_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description       .
        /// </summary>
        public static string Security_IUserRolePermission_Description_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Description_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the permission group that the permission belongs to..
        /// </summary>
        public static string Security_IUserRolePermission_GroupName_Description {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_GroupName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Group Name.
        /// </summary>
        public static string Security_IUserRolePermission_GroupName_Name {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_GroupName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Security_IUserRolePermission_GroupName_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_GroupName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the application module that the permission belongs to..
        /// </summary>
        public static string Security_IUserRolePermission_ModuleName_Description {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_ModuleName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string Security_IUserRolePermission_ModuleName_Name {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_ModuleName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Security_IUserRolePermission_ModuleName_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_ModuleName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the assignable permission..
        /// </summary>
        public static string Security_IUserRolePermission_Name_Description {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name.
        /// </summary>
        public static string Security_IUserRolePermission_Name_Name {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name       .
        /// </summary>
        public static string Security_IUserRolePermission_Name_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserRolePermission_Name_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role For Tenant           .
        /// </summary>
        public static string Security_IUserTenant_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_IUserTenant_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user role for the tenant..
        /// </summary>
        public static string Security_IUserTenant_Role_Description {
            get {
                return ResourceManager.GetString("Security_IUserTenant_Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string Security_IUserTenant_Role_Name {
            get {
                return ResourceManager.GetString("Security_IUserTenant_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify user role..
        /// </summary>
        public static string Security_IUserTenant_Role_Prompt {
            get {
                return ResourceManager.GetString("Security_IUserTenant_Role_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Security_IUserTenant_Role_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserTenant_Role_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name of the tenant to set a user role for..
        /// </summary>
        public static string Security_IUserTenant_TenantName_Description {
            get {
                return ResourceManager.GetString("Security_IUserTenant_TenantName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string Security_IUserTenant_TenantName_Name {
            get {
                return ResourceManager.GetString("Security_IUserTenant_TenantName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name       .
        /// </summary>
        public static string Security_IUserTenant_TenantName_ShortName {
            get {
                return ResourceManager.GetString("Security_IUserTenant_TenantName_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email of the user that is used as a user account id..
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Email_Description {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Email_Name {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Email_Prompt {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Email_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Email_ShortName {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Email_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password..
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Password_Description {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Password_Name {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Password_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password..
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Password_Prompt {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Password_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password.
        /// </summary>
        public static string Security_LoginRequestQueryCriteria_Password_ShortName {
            get {
                return ResourceManager.GetString("Security_LoginRequestQueryCriteria_Password_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password       .
        /// </summary>
        public static string Security_ResetPasswordRequestQueryCriteria_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_ResetPasswordRequestQueryCriteria_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user email that is used as the app account id..
        /// </summary>
        public static string Security_ResetPasswordRequestQueryCriteria_Email_Description {
            get {
                return ResourceManager.GetString("Security_ResetPasswordRequestQueryCriteria_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string Security_ResetPasswordRequestQueryCriteria_Email_Name {
            get {
                return ResourceManager.GetString("Security_ResetPasswordRequestQueryCriteria_Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Security_ResetPasswordRequestQueryCriteria_Email_Prompt {
            get {
                return ResourceManager.GetString("Security_ResetPasswordRequestQueryCriteria_Email_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string Security_ResetPasswordRequestQueryCriteria_Email_ShortName {
            get {
                return ResourceManager.GetString("Security_ResetPasswordRequestQueryCriteria_Email_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Index.
        /// </summary>
        public static string Security_TenantQueryResult_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of the users that have access to the tenant data (excluding user group admins)..
        /// </summary>
        public static string Security_TenantQueryResult_UserCount_Description {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_UserCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string Security_TenantQueryResult_UserCount_Name {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_UserCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Security_TenantQueryResult_UserCount_ShortName {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_UserCount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User groups that have access to the tenant data..
        /// </summary>
        public static string Security_TenantQueryResult_UserGroups_Description {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_UserGroups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string Security_TenantQueryResult_UserGroups_Name {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_UserGroups_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string Security_TenantQueryResult_UserGroups_ShortName {
            get {
                return ResourceManager.GetString("Security_TenantQueryResult_UserGroups_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Login Second Step.
        /// </summary>
        public static string Security_TwoFactorLoginRequest_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_TwoFactorLoginRequest_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A two factor authentication token that has been sent to you after the first login step..
        /// </summary>
        public static string Security_TwoFactorLoginRequest_Token_Description {
            get {
                return ResourceManager.GetString("Security_TwoFactorLoginRequest_Token_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Security_TwoFactorLoginRequest_Token_Name {
            get {
                return ResourceManager.GetString("Security_TwoFactorLoginRequest_Token_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the token you received..
        /// </summary>
        public static string Security_TwoFactorLoginRequest_Token_Prompt {
            get {
                return ResourceManager.GetString("Security_TwoFactorLoginRequest_Token_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Security_TwoFactorLoginRequest_Token_ShortName {
            get {
                return ResourceManager.GetString("Security_TwoFactorLoginRequest_Token_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign admin to any user group..
        /// </summary>
        public static string Security_User_Cannot_Assign_Admin_UserGroup {
            get {
                return ResourceManager.GetString("Security_User_Cannot_Assign_Admin_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Security_UserGroupLookup_ToString {
            get {
                return ResourceManager.GetString("Security_UserGroupLookup_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group Index.
        /// </summary>
        public static string Security_UserGroupQueryResult_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_UserGroupQueryResult_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual count of tenants assigned to the group..
        /// </summary>
        public static string Security_UserGroupQueryResult_TenantCount_Description {
            get {
                return ResourceManager.GetString("Security_UserGroupQueryResult_TenantCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Count.
        /// </summary>
        public static string Security_UserGroupQueryResult_TenantCount_Name {
            get {
                return ResourceManager.GetString("Security_UserGroupQueryResult_TenantCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string Security_UserGroupQueryResult_TenantCount_ShortName {
            get {
                return ResourceManager.GetString("Security_UserGroupQueryResult_TenantCount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom user permissions are configured..
        /// </summary>
        public static string Security_UserRoleLookup_Custom_Role_Description {
            get {
                return ResourceManager.GetString("Security_UserRoleLookup_Custom_Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Role.
        /// </summary>
        public static string Security_UserRoleLookup_Custom_Role_Name {
            get {
                return ResourceManager.GetString("Security_UserRoleLookup_Custom_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Index.
        /// </summary>
        public static string Security_UserRoleQueryResult_DisplayNameForNew {
            get {
                return ResourceManager.GetString("Security_UserRoleQueryResult_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Index.
        /// </summary>
        public static string UserQueryResult_DisplayNameForNew {
            get {
                return ResourceManager.GetString("UserQueryResult_DisplayNameForNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles that the user has..
        /// </summary>
        public static string UserQueryResult_Roles_Description {
            get {
                return ResourceManager.GetString("UserQueryResult_Roles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string UserQueryResult_Roles_Name {
            get {
                return ResourceManager.GetString("UserQueryResult_Roles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string UserQueryResult_Roles_ShortName {
            get {
                return ResourceManager.GetString("UserQueryResult_Roles_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tenants that the user has access to..
        /// </summary>
        public static string UserQueryResult_TenantCount_Description {
            get {
                return ResourceManager.GetString("UserQueryResult_TenantCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Count.
        /// </summary>
        public static string UserQueryResult_TenantCount_Name {
            get {
                return ResourceManager.GetString("UserQueryResult_TenantCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string UserQueryResult_TenantCount_ShortName {
            get {
                return ResourceManager.GetString("UserQueryResult_TenantCount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for document {0} is invalid:
        ///{1}.
        /// </summary>
        public static string ValidationException_Message {
            get {
                return ResourceManager.GetString("ValidationException_Message", resourceCulture);
            }
        }
    }
}
