//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A5Soft.A5App.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A5Soft.A5App.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password..
        /// </summary>
        public static string ApplicationMenu_ChangePasswordMenuItem_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_ChangePasswordMenuItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ApplicationMenu_ChangePasswordMenuItem_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_ChangePasswordMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common application settings and user administration..
        /// </summary>
        public static string ApplicationMenu_CommonGroup_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_CommonGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string ApplicationMenu_CommonGroup_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_CommonGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to a tenant database..
        /// </summary>
        public static string ApplicationMenu_LoginTenantMenuGroup_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_LoginTenantMenuGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Tenant.
        /// </summary>
        public static string ApplicationMenu_LoginTenantMenuGroup_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_LoginTenantMenuGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User administration actions..
        /// </summary>
        public static string ApplicationMenu_UserAdminMenuGroup_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_UserAdminMenuGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        public static string ApplicationMenu_UserAdminMenuGroup_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_UserAdminMenuGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group index..
        /// </summary>
        public static string ApplicationMenu_UserGroupsMenuItem_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_UserGroupsMenuItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string ApplicationMenu_UserGroupsMenuItem_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_UserGroupsMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role index.
        /// </summary>
        public static string ApplicationMenu_UserRolesMenuItem_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_UserRolesMenuItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string ApplicationMenu_UserRolesMenuItem_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_UserRolesMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User index..
        /// </summary>
        public static string ApplicationMenu_UsersMenuItem_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_UsersMenuItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string ApplicationMenu_UsersMenuItem_Name {
            get {
                return ResourceManager.GetString("ApplicationMenu_UsersMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to {0}..
        /// </summary>
        public static string AuthorizationException_Message {
            get {
                return ResourceManager.GetString("AuthorizationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new user.
        /// </summary>
        public static string DefaultPermissions_Admin_CreateUser_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_CreateUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a user group.
        /// </summary>
        public static string DefaultPermissions_Admin_CreateUserGroup_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_CreateUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a new user role.
        /// </summary>
        public static string DefaultPermissions_Admin_CreateUserRole_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_CreateUserRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete a user.
        /// </summary>
        public static string DefaultPermissions_Admin_DeleteUser_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_DeleteUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete a user group.
        /// </summary>
        public static string DefaultPermissions_Admin_DeleteUserGroup_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_DeleteUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete a user role.
        /// </summary>
        public static string DefaultPermissions_Admin_DeleteUserRole_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_DeleteUserRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch a custom user role.
        /// </summary>
        public static string DefaultPermissions_Admin_FetchCustomUserRole_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_FetchCustomUserRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch tenant assignments to user groups.
        /// </summary>
        public static string DefaultPermissions_Admin_FetchTenantGroupAssignment_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_FetchTenantGroupAssignment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch a user data.
        /// </summary>
        public static string DefaultPermissions_Admin_FetchUser_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_FetchUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch a user group.
        /// </summary>
        public static string DefaultPermissions_Admin_FetchUserGroup_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_FetchUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch a user role.
        /// </summary>
        public static string DefaultPermissions_Admin_FetchUserRole_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_FetchUserRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query tenants.
        /// </summary>
        public static string DefaultPermissions_Admin_QueryTenants_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_QueryTenants_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query user groups.
        /// </summary>
        public static string DefaultPermissions_Admin_QueryUserGroups_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_QueryUserGroups_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query user roles.
        /// </summary>
        public static string DefaultPermissions_Admin_QueryUserRoles_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_QueryUserRoles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query users.
        /// </summary>
        public static string DefaultPermissions_Admin_QueryUsers_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_QueryUsers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a custom user role for tenant.
        /// </summary>
        public static string DefaultPermissions_Admin_UpdateCustomUserRole_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_UpdateCustomUserRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tenant assignment to user groups.
        /// </summary>
        public static string DefaultPermissions_Admin_UpdateTenantGroupAssignment_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_UpdateTenantGroupAssignment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a user data.
        /// </summary>
        public static string DefaultPermissions_Admin_UpdateUser_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_UpdateUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a user group.
        /// </summary>
        public static string DefaultPermissions_Admin_UpdateUserGroup_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_UpdateUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update a user role.
        /// </summary>
        public static string DefaultPermissions_Admin_UpdateUserRole_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Admin_UpdateUserRole_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string DefaultPermissions_ModuleName_Security {
            get {
                return ResourceManager.GetString("DefaultPermissions_ModuleName_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permission to access audit trace data for documents (created at, created by, last updated at, last updated by)..
        /// </summary>
        public static string DefaultPermissions_Security_AccessAuditTrace_Description {
            get {
                return ResourceManager.GetString("DefaultPermissions_Security_AccessAuditTrace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access audit trace.
        /// </summary>
        public static string DefaultPermissions_Security_AccessAuditTrace_Name {
            get {
                return ResourceManager.GetString("DefaultPermissions_Security_AccessAuditTrace_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string DefaultPermissions_Security_GroupName_Security {
            get {
                return ResourceManager.GetString("DefaultPermissions_Security_GroupName_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Tenant.
        /// </summary>
        public static string LoginTenantMenuItem_Logout {
            get {
                return ResourceManager.GetString("LoginTenantMenuItem_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is not specified for entity to delete of type {0}..
        /// </summary>
        public static string No_Id_For_Deleted_Entity {
            get {
                return ResourceManager.GetString("No_Id_For_Deleted_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is not specified for entity to update of type {0}..
        /// </summary>
        public static string No_Id_For_Updated_Entity {
            get {
                return ResourceManager.GetString("No_Id_For_Updated_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found (id = {1})..
        /// </summary>
        public static string NotFoundException_Message {
            get {
                return ResourceManager.GetString("NotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid..
        /// </summary>
        public static string Security_ChangePasswordUseCase_Password_Invalid {
            get {
                return ResourceManager.GetString("Security_ChangePasswordUseCase_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled..
        /// </summary>
        public static string Security_ConfirmResetPasswordUseCase_Account_Disabled {
            get {
                return ResourceManager.GetString("Security_ConfirmResetPasswordUseCase_Account_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group administrators cannot create users that wouldn&apos;t belong to the group they administrate..
        /// </summary>
        public static string Security_CreateUserUseCase_Cannot_Create_For_Other_Group {
            get {
                return ResourceManager.GetString("Security_CreateUserUseCase_Cannot_Create_For_Other_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group administrators cannot create users with administrative privileges..
        /// </summary>
        public static string Security_CreateUserUseCase_Cannot_Create_With_Admin_Privileges {
            get {
                return ResourceManager.GetString("Security_CreateUserUseCase_Cannot_Create_With_Admin_Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group administrators cannot create users that wouldn&apos;t belong to any group..
        /// </summary>
        public static string Security_CreateUserUseCase_Cannot_Create_Without_Group {
            get {
                return ResourceManager.GetString("Security_CreateUserUseCase_Cannot_Create_Without_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group already has maximum allowed user count..
        /// </summary>
        public static string Security_CreateUserUseCase_User_Group_Already_Full {
            get {
                return ResourceManager.GetString("Security_CreateUserUseCase_User_Group_Already_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a user group that has assigned users..
        /// </summary>
        public static string Security_DeleteUserGroupUseCase_Cannot_Delete_Non_Empty_UserGroup {
            get {
                return ResourceManager.GetString("Security_DeleteUserGroupUseCase_Cannot_Delete_Non_Empty_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a user role that is assigned to active (not disabled) users..
        /// </summary>
        public static string Security_DeleteUserRoleUseCase_Cannot_Delete_Role_In_Use {
            get {
                return ResourceManager.GetString("Security_DeleteUserRoleUseCase_Cannot_Delete_Role_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group administrators cannot delete users that do not belong to any user group..
        /// </summary>
        public static string Security_DeleteUserUseCase_Cannot_Delete_Null_Group {
            get {
                return ResourceManager.GetString("Security_DeleteUserUseCase_Cannot_Delete_Null_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group administrators cannot delete users that belong to other user groups..
        /// </summary>
        public static string Security_DeleteUserUseCase_Cannot_Delete_Other_Group {
            get {
                return ResourceManager.GetString("Security_DeleteUserUseCase_Cannot_Delete_Other_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No harakiri..
        /// </summary>
        public static string Security_DeleteUserUseCase_No_Harakiri {
            get {
                return ResourceManager.GetString("Security_DeleteUserUseCase_No_Harakiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch a custom user role for a user that does not belong to the user group.
        /// </summary>
        public static string Security_FetchCustomUserRoleUseCase_No_Fetch_For_Other_UserGroups {
            get {
                return ResourceManager.GetString("Security_FetchCustomUserRoleUseCase_No_Fetch_For_Other_UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch custom user role for self.
        /// </summary>
        public static string Security_FetchCustomUserRoleUseCase_No_Self_Fetch {
            get {
                return ResourceManager.GetString("Security_FetchCustomUserRoleUseCase_No_Self_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetch self data.
        /// </summary>
        public static string Security_FetchUserUseCase_No_Self_Fetch {
            get {
                return ResourceManager.GetString("Security_FetchUserUseCase_No_Self_Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access data of admin users.
        /// </summary>
        public static string Security_FetchUserUseCase_Unauthorized_Admin_Fetch_By_GroupAdmin {
            get {
                return ResourceManager.GetString("Security_FetchUserUseCase_Unauthorized_Admin_Fetch_By_GroupAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access data of the users outside of your group.
        /// </summary>
        public static string Security_FetchUserUseCase_Unauthorized_For_GroupAdmin {
            get {
                return ResourceManager.GetString("Security_FetchUserUseCase_Unauthorized_For_GroupAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access the tenant data..
        /// </summary>
        public static string Security_LoginTenantUseCase_NotAuthorized {
            get {
                return ResourceManager.GetString("Security_LoginTenantUseCase_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled..
        /// </summary>
        public static string Security_LoginUseCase_Account_Disabled {
            get {
                return ResourceManager.GetString("Security_LoginUseCase_Account_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been temporally suspended due to multiple failed logins. Lockout will end in {0} min. {1} sec..
        /// </summary>
        public static string Security_LoginUseCase_Account_LockedOut {
            get {
                return ResourceManager.GetString("Security_LoginUseCase_Account_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password or email..
        /// </summary>
        public static string Security_LoginUseCase_Invalid_Password_Or_Email {
            get {
                return ResourceManager.GetString("Security_LoginUseCase_Invalid_Password_Or_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset password for disabled account.
        /// </summary>
        public static string Security_ResetPasswordUseCase_Cannot_Reset_For_Disabled_Account {
            get {
                return ResourceManager.GetString("Security_ResetPasswordUseCase_Cannot_Reset_For_Disabled_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set custom user roles for users that do not belong to his group.
        /// </summary>
        public static string Security_UpdateCustomUserRoleUseCase_Cannot_Set_For_Other_UserGroups {
            get {
                return ResourceManager.GetString("Security_UpdateCustomUserRoleUseCase_Cannot_Set_For_Other_UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set custom user role for self.
        /// </summary>
        public static string Security_UpdateCustomUserRoleUseCase_Cannot_Set_For_Self {
            get {
                return ResourceManager.GetString("Security_UpdateCustomUserRoleUseCase_Cannot_Set_For_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot grant administrative privileges..
        /// </summary>
        public static string Security_UpdateUserUseCase_Cannot_Grant_Admin {
            get {
                return ResourceManager.GetString("Security_UpdateUserUseCase_Cannot_Grant_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update data about self.
        /// </summary>
        public static string Security_UpdateUserUseCase_Cannot_Update_Self {
            get {
                return ResourceManager.GetString("Security_UpdateUserUseCase_Cannot_Update_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update user group..
        /// </summary>
        public static string Security_UpdateUserUseCase_Cannot_Update_UserGroup {
            get {
                return ResourceManager.GetString("Security_UpdateUserUseCase_Cannot_Update_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update users with administrative privileges.
        /// </summary>
        public static string Security_UpdateUserUseCase_No_Update_Admin_Users {
            get {
                return ResourceManager.GetString("Security_UpdateUserUseCase_No_Update_Admin_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update users who belong to other user groups.
        /// </summary>
        public static string Security_UpdateUserUseCase_No_Update_For_Other_Groups {
            get {
                return ResourceManager.GetString("Security_UpdateUserUseCase_No_Update_For_Other_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not logged in..
        /// </summary>
        public static string UnAuthenticatedException_Message {
            get {
                return ResourceManager.GetString("UnAuthenticatedException_Message", resourceCulture);
            }
        }
    }
}
